version: 2.1

orbs:
  python: circleci/python@1.2

workflows:
  sample:  
    jobs:
      - build-and-test


jobs:
  build-and-test:
    machine: # executor type
      image: ubuntu-2004:202010-01 
    steps:
      - checkout
      - run:
          name: Run tests
          command: nvidia-smi
