version: 2.1

orbs:
  welcome: circleci/welcome-orb@0.4.1

workflows:
  sample:  
    jobs:
      - build-and-test


jobs:
  build-and-test: 
    machine: # executor type
      image: ubuntu-2004:202010-01
    steps:
      - checkout
      - run:
          name: Run tests
          command: echo hello

