version: 2.1

orbs:
  python: circleci/python@1.2

jobs:
  build-and-test:
    executor: python/default
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
      - run:
          name: pytest
          command: "pytest --version"

workflows:
  python:  
    jobs:
      - build-and-test